### ISSUE TITLE
dockerapi returns 404 on system information

### ISSUE THREAD

**Issue by adriantalpa** [maxtroughear/docker-images#1]
Hi,
First of all, thanks for the work to port this to arm64! I was looking into this myself but now you saved me precious time.

I managed to spin up mailcow but I was wondering if you have any idea why would the dockerapi container returns 404 when trying to monitor the host/containers in the System information are of the web UI.

- Go to System > Indormation
- `docker logs mailcowdockerized-dockerapi-mailcow-1`
```
172.22.1.9 - - [02/Mar/2023 19:39:20] "POST /containers/48b7965ed6612599f474bceab4d0a0a695a869190c8f5f444ee7bd3abf59c058/exec HTTP/1.1" 200 -
172.22.1.9 - - [02/Mar/2023 19:39:20] "GET /containers/json HTTP/1.1" 200 -
172.22.1.9 - - [02/Mar/2023 19:39:21] "GET /host/stats HTTP/1.1" 404 -
172.22.1.9 - - [02/Mar/2023 19:39:26] "GET /host/stats HTTP/1.1" 404 -
172.22.1.9 - - [02/Mar/2023 19:39:32] "GET /host/stats HTTP/1.1" 404 -
```

Using mailcow latest version on a x86 arch this was working fine. I wonder if this is an issue because of the arm arch. Before I get some time to dig into this, I thought to ask you what do you think?

Cheers,
Adrian

**Comment by adriantalpa** [comment]
Hi,
for now, looks like building the dockerapi-mailcow image myself on the server fixes the problem.

1. 
```
cd data/Dockerfiles/dockerapi/
docker build -t dockerapi-mailcow:local .
```
2. Replace image name inside `docker-compose.override.yml` for `dockerapi-mailcow` service: `image: dockerapi-mailcow:local`.
3. Relaunch stack.

I think something is broken in the build process in g/h actions and something slips out of the process. Hope to have a look soon.


-A

**Comment by maxtroughear** [comment]
Hi,

Thanks for reporting this. I'll investigate on my end tonight and will also update everything to the latest release of mailcow given the recent CVE patch.

At first glance I wouldn't be surprised if it is due to out of date images on my behalf.

Cheers,
Max

**Comment by adriantalpa** [comment]
Hi Max,
thanks for your reply.

In the meantime, I did a patch to quick build local images from the latest mailcow.  See it [here](https://github.com/maxtroughear/docker-images/compare/main...adriantalpa:mailcow-dockerized-arm64:local-img-build).
Dovecot's Dockerfile was the only one not building locally. Also, did some quick changes to allow the launch of the stack using the original docker-compose.yml from mailcow (this needs to `sed`'ed better). I'm sure the process can be improved to follow mailcow's tags for the images... now it's "latest".

PS: can integrate this way of patching into your master and post a PR if interested...

-A

**Comment by maxtroughear** [comment]
Hi,

Apologies for the delay, I've been working on building dovecot from source to address the following
- Match the version used in the mailcow-dockerized project
- Move away from using the testing release of debian

So far I have a working test environment, however I still need to perform some more in depth testing.

Once this is complete I can look to make the install and update processes smoother and/or incorporate the changes as you've suggest.

Thanks,
Max

**Comment by adriantalpa** [comment]
That's great. Thanks.
-A

**Comment by maxtroughear** [comment]
I've been running this in my live environment for a couple of days now and appears stable for my usage.
Please let me know if you run into any issues going forward.
